### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by supriyanta**

### CODE REVIEW

**Comment by flcdrg** [comment]
The file is empty. Is that intended?

**Comment by supriyanta** [comment]
Yes, I added this file. Because maintainers can write some guidelines about how to contribute!

**Comment by flcdrg** [comment]
Ok.. and https://github.com/Microsoft/Hacktoberfest#contributing didn't cover what you were expecting?

**Comment by supriyanta** [comment]
Okay, There is no issue to work on. Please add some beginner issues to work on.

**Comment by berndverst** [comment]
Closing because this doesn't meaningfully improve anything.

**Pull request closed without merging**
